name: tag-workflow

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [custom-event]
env:
  IMAGE_NAME: print 
  DOC_USER: ${{ secrets.DOCKERHUB_USERNAME }} 
  DOC_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print image tag
        run: |
          echo "$DOC_PASS" | docker login -u "$DOC_USER" --password-stdin
          docker pull $DOC_USER/$IMAGE_NAME --all-tags
          echo "Latest tag for docker image"
          docker images | grep -m 1 $DOC_USER | awk '{print $2}'
          





